document.addEventListener('DOMContentLoaded', () => {
    // 1. Header Scroll Effect
    window.addEventListener('scroll', () => {
        document.getElementById('mainHeader').classList.toggle('scrolled', window.scrollY > 50);
    });

    // 2. Dark Mode Logic
    const themeToggles = document.querySelectorAll('.theme-toggle');
    const rootElement = document.documentElement;

    function setTheme(theme) {
        if (theme === 'dark') {
            rootElement.setAttribute('data-theme', 'dark');
            themeToggles.forEach(t => t.textContent = '☀️');
            localStorage.setItem('theme', 'dark');
        } else {
            rootElement.removeAttribute('data-theme');
            themeToggles.forEach(t => t.textContent = '🌙');
            localStorage.setItem('theme', 'light');
        }
    }

    const savedTheme = localStorage.getItem('theme');
    if (savedTheme) {
        setTheme(savedTheme);
    } else if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
        setTheme('dark');
    }

    themeToggles.forEach(btn => {
        btn.addEventListener('click', () => {
            const current = rootElement.getAttribute('data-theme') === 'dark' ? 'light' : 'dark';
            setTheme(current);
        });
    });

    // 3. Scroll Reveal Animations
    const observerOptions = { threshold: 0.1, rootMargin: '0px 0px -50px 0px' };
    const observer = new IntersectionObserver((entries) => {
        entries.forEach(entry => {
            if (entry.isIntersecting) {
                entry.target.classList.add('active');
            }
        });
    }, observerOptions);

    document.querySelectorAll('.reveal').forEach(el => observer.observe(el));

    // 4. Filter Logic for Gallery
    const categoryBtns = document.querySelectorAll('.work-categories a');
    const artworkCards = document.querySelectorAll('.artwork-card');
    categoryBtns.forEach(btn => {
        btn.addEventListener('click', function(e) {
            e.preventDefault();
            categoryBtns.forEach(b => b.classList.remove('active'));
            this.classList.add('active');
            
            const filterValue = this.innerText.toLowerCase();
            
            artworkCards.forEach(card => {
                const cardCategory = card.querySelector('.artwork-overlay span').innerText.toLowerCase();
                if (filterValue === 'all' || filterValue === 'view all' || cardCategory.includes(filterValue)) {
                    card.style.display = 'block';
                } else {
                    card.style.display = 'none';
                }
            });
        });
    });
});

// 5. Mobile Menu Toggle
function toggleMenu() {
    document.querySelector('.hamburger').classList.toggle('active');
    document.querySelector('.mobile-menu').classList.toggle('active');
    document.querySelector('.overlay').classList.toggle('active');
    document.body.style.overflow = document.querySelector('.mobile-menu').classList.contains('active') ? 'hidden' : '';
}

// 6. Unified Action Modal Logic (Sign Up / Work / Follow)
function openActionModal(defaultTab = 'tab-signup') {
    const modal = document.getElementById('actionModal');
    if (modal) {
        modal.classList.add('active');
        document.body.style.overflow = 'hidden';
        const targetBtn = document.querySelector(`.tab-btn[onclick*="${defaultTab}"]`);
        if(targetBtn) targetBtn.click();
    }
}

function closeActionModal() {
    const modal = document.getElementById('actionModal');
    if (modal) {
        modal.classList.remove('active');
        document.body.style.overflow = '';
    }
}

function switchTab(evt, tabId) {
    document.querySelectorAll('.tab-panel').forEach(panel => panel.classList.remove('active'));
    document.querySelectorAll('.tab-btn').forEach(btn => btn.classList.remove('active'));
    document.getElementById(tabId).classList.add('active');
    evt.currentTarget.classList.add('active');
}

// Close action modal on outside click
document.addEventListener('click', function(e) {
    const modal = document.getElementById('actionModal');
    if (modal && e.target === modal) closeActionModal();
});

// ==========================================
// DYNAMIC GALLERY RENDERER (HEADLESS CMS)
// ==========================================
async function loadArtworks() {
    const galleryGrid = document.querySelector('.gallery-grid');
    
    // If we aren't on a page with a gallery, stop here
    if (!galleryGrid) return; 

    try {
        // 1. Fetch the JSON file generated by Decap CMS
        const response = await fetch('data/artworks/index.json');
        if (!response.ok) throw new Error('Could not fetch artworks');
        
        const data = await response.json();
        
        // 2. Handle the data (Decap CMS creates an object with an 'artworks' array)
        let artworks = [];
        if (data && data.artworks) {
            artworks = data.artworks;
        } else if (Array.isArray(data)) {
            artworks = data;
        }

        // 3. If Promise uploaded art, wipe the placeholders and inject the real art!
        if (artworks.length > 0) {
            galleryGrid.innerHTML = ''; // Clears out the dummy placeholders
            
            artworks.forEach((art, index) => {
                // Create the card
                const card = document.createElement('div');
                card.className = 'artwork-card reveal active'; 
                
                // Format the category text nicely (e.g. "3d-art" -> "3d art")
                const cleanCategory = art.category ? art.category.replace('-', ' ') : 'Artwork';

                // Wire up the Modal click event with the real CMS data
                card.onclick = () => openModal(
                    art.title || 'Untitled', 
                    cleanCategory, 
                    art.image, 
                    art.cropImage || art.image // Fallback to main image if no crop provided
                );

                // Build the HTML structure for the card
                card.innerHTML = `
                    <div class="artwork-image">
                        <img src="${art.image}" alt="${art.title}" onerror="this.style.display='none'; this.parentElement.style.background='linear-gradient(135deg, var(--color-dominant), var(--color-compliment))'">
                    </div>
                    <div class="artwork-overlay">
                        <h3>${art.title || 'Untitled'}</h3>
                        <span>${cleanCategory}</span>
                    </div>
                `;
                
                // Inject it into the page
                galleryGrid.appendChild(card);
            });

            // 4. Re-initialize the Category Filters so they work on the newly injected art
            initializeFilters();
        }
    } catch (error) {
        console.log('CMS Data not found or empty. Showing default placeholders.', error);
    }
}

// Wrapping your filter logic in a function so we can call it after the CMS loads
function initializeFilters() {
    const categoryBtns = document.querySelectorAll('.work-categories a');
    const artworkCards = document.querySelectorAll('.artwork-card');
    
    categoryBtns.forEach(btn => {
        // Remove old listeners to prevent duplicates
        const newBtn = btn.cloneNode(true);
        btn.parentNode.replaceChild(newBtn, btn);
        
        newBtn.addEventListener('click', function(e) {
            e.preventDefault();
            // Remove active class from all
            document.querySelectorAll('.work-categories a').forEach(b => b.classList.remove('active'));
            // Add to clicked
            this.classList.add('active');
            
            const filterValue = this.innerText.toLowerCase();
            
            document.querySelectorAll('.artwork-card').forEach(card => {
                const cardCategory = card.querySelector('.artwork-overlay span').innerText.toLowerCase();
                if (filterValue === 'all' || filterValue === 'view all' || cardCategory.includes(filterValue)) {
                    card.style.display = 'block';
                } else {
                    card.style.display = 'none';
                }
            });
        });
    });
}

// Fire the function immediately when the page loads!
document.addEventListener('DOMContentLoaded', () => {
    loadArtworks();
});
