backend:
  name: github
  repo: Son-of-IAM/WEBSITE---Artwork_Showcase
  branch: main

media_folder: "Images/artworks"
public_folder: "Images/artworks"

collections:
  - name: "artworks_data"
    label: "Artwork Manager"
    files:
      - label: "Gallery Database"
        name: "gallery"
        file: "data/artworks/index.json" # Points directly to your JSON file!
        fields:
          - label: "Artworks List"
            name: "artworks"
            widget: "list" # This creates an array [] inside the JSON
            summary: '{{fields.title}} - {{fields.category}}'
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Category"
                name: "category"
                widget: "select"
                options:
                  - "paintings"
                  - "3d-art"
                  - "gospel"
                  - "old"
                  - "graffiti"
              - label: "Main Image"
                name: "image"
                widget: "image"
              - label: "Cropped Detail"
                name: "cropImage"
                widget: "image"
                required: false
